AddonId: 'HeliumWithTabs-8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2'
Packages:
  - Version: 4.0.0
    RequiredApiVersion: 2.9.0
    ReleaseDate: 2026-02-27
    PackageUrl: https://github.com/tetj/HeliumWithTabs/releases/download/v4/HeliumWithTabs-8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2_4_0.pthm
    Changelog:
      - First release
